Dev
crm-final-project/crm_api pull request #22
Opened 2022-04-26 12:40 UTC by adebudev

2022-04-26 19:25 UTC, andreshugueth requested changes

2022-04-26 19:25 UTC, andreshugueth commented on requirements.txt
> +autopep8==1.6.0
please delete autopep8

2022-04-26 19:25 UTC, andreshugueth commented on requirements.txt
> +h11==0.12.0
lets maintain h11==0.13.0

2022-04-27 19:46 UTC, adebudev commented on requirements.txt
> +SQLAlchemy==1.4.32
```suggestion
SQLAlchemy==1.4.23
```

2022-04-27 23:29 UTC, andreshugueth approved these changes

2022-04-27 23:32 UTC, merged